# -*- coding: utf-8 -*-
"""house_price_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjZOsI8B6iDS8JA4jgmWKr9EM8-4qYqF
"""

# Task 1: Create synthetic dataset and train model

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Create synthetic data
np.random.seed(42)

n = 100

data = pd.DataFrame({
    "area_sqft": np.random.randint(500, 3000, n),
    "num_bedrooms": np.random.randint(1, 5, n),
    "age_years": np.random.randint(0, 30, n)
})

# Create target with some realistic relationship
data["price_lakhs"] = (
    data["area_sqft"] * 0.05 +
    data["num_bedrooms"] * 10 -
    data["age_years"] * 0.3 +
    np.random.normal(0, 5, n)  # noise
)

# Features and target
X = data[["area_sqft", "num_bedrooms", "age_years"]]
y = data["price_lakhs"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Print intercept and coefficients
print("Intercept:", model.intercept_)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})
print("\nCoefficients:\n", coefficients)

# Predictions
y_pred = model.predict(X_test)

# Show first 5 actual vs predicted
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print("\nFirst 5 Predictions:\n", comparison.head())

# Task 2: Evaluation

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\nMAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

# Explanation:
# MAE tells the average absolute error between predicted and actual prices.
# RMSE penalizes larger errors more heavily, giving a sense of error magnitude.
# R² indicates how well the model explains variance (closer to 1 is better).

# Task 3: Residuals and visualization

import matplotlib.pyplot as plt

# Residuals
residuals = y_test - y_pred

# Plot histogram
plt.hist(residuals)
plt.title("Residual Distribution")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

# Explanation:
# A residual is the difference between actual and predicted values.
# If the histogram is roughly symmetric and centered around zero,
# it suggests the model errors are unbiased and reasonably well-behaved.